openapi: 3.0.2

info:
  title: XT3 API
  version: 0.0.1

servers:
  - url: 'http://localhost:8080'
    description: 'Local Environment'

paths:
  /tweets:
    get:
      tags:
        - tweets
      summary: Get all tweets
      description: Returns all tweets. This api is for debug.
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTweetsRes'
        '401':
          description: unauthorized
    post:
      tags:
        - tweets
      summary: Post a tweet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TweetReq'
      responses:
        '201':
          description: success
        '401':
          description: unauthorized
        '5XX':
          description: internal server error
  /tweets/{tweetId}:
    get:
      tags:
        - tweets
      summary: Get tweet by ID
      description: Returns a tweet
      parameters:
        - name: tweetId
          in: path
          description: ID of tweet to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 'success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTweetsByTweetIdRes'
        '400':
          description: no tweet
        '401':
          description: unauthorized
        '404':
          description: tweet not found
  /accounts/{accountId}:
    get:
      tags:
        - accounts
      summary: Get account by ID
      description: Returns an account information
      parameters:
        - name: accountId
          in: path
          description: ID of account to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 'success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountRes'
        '400':
          description: no account id
        '401':
          description: unauthorized
        '404':
          description: account not found

components:
  schemas:
    TweetReq:
      required:
        - tweetText
        - accountId
      type: object
      properties:
        tweetText:
          type: string
          example: Now Tweet!
        accountId:
          type: integer
          format: int64
          example: 1
    TweetRes:
      required:
        - tweetId
        - tweetText
        - accountId
        - createdAt
      type: object
      properties:
        tweetId:
          type: integer
          format: int64
          example: 20
        tweetText:
          type: string
          example: just setting up my twttr
        accountId:
          type: integer
          format: int64
          example: 1
        createdAt:
          type: string
          format: date-time
    GetTweetsRes:
      required:
        - total
        - tweets
      type: object
      properties:
        total:
          type: integer
          example: 10
        tweets:
          type: array
          items:
            $ref: '#/components/schemas/TweetRes'
    GetTweetsByTweetIdRes:
      required:
        - data
        - include
      type: object
      properties:
        data:
          $ref: '#/components/schemas/TweetRes'
        include:
          type: array
          items:
            $ref: '#/components/schemas/TweetRes'
    AccountRes:
      required:
        - accountId
        - displayName
        - accountName
        - profileDescription
        - createdAt
      type: object
      properties:
        accountId:
          type: integer
          format: int64
          example: 1
        displayName:
          type: string
          example: Djack
        accountName:
          type: string
          example: jack
        profileDescription:
          type: string
          example: bitcoin and chill
        profileImageUrl:
          type: string
          example: https://example.com/profile_image.jpg

